# Generated by Django 2.2.3 on 2019-07-22 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='scapp',
        ),
    ]
