# Generated by Django 2.1.1 on 2019-08-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], default='★', max_length=6),
        ),
    ]
