# Generated by Django 2.1.1 on 2019-08-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20190806_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='star',
        ),
        migrations.RemoveField(
            model_name='review',
            name='time',
        ),
        migrations.AddField(
            model_name='review',
            name='fun',
            field=models.CharField(choices=[('★★★★★', '★★★★★'), ('★', '★'), ('★★★★', '★★★★'), ('★★★', '★★★'), ('★★', '★★')], default='★', max_length=5),
        ),
        migrations.AddField(
            model_name='review',
            name='runningtime',
            field=models.CharField(choices=[('★★★★★', '★★★★★'), ('★', '★'), ('★★★★', '★★★★'), ('★★★', '★★★'), ('★★', '★★')], default='★', max_length=5),
        ),
        migrations.AddField(
            model_name='review',
            name='volume',
            field=models.CharField(choices=[('★★★★★', '★★★★★'), ('★', '★'), ('★★★★', '★★★★'), ('★★★', '★★★'), ('★★', '★★')], default='★', max_length=5),
        ),
    ]
