# Generated by Django 2.1.1 on 2019-08-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20190806_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='fun',
            field=models.IntegerField(choices=[('5', '★★★★★'), ('2', '★★'), ('3', '★★★'), ('1', '★'), ('4', '★★★★')], default='★', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='runningtime',
            field=models.IntegerField(choices=[('5', '★★★★★'), ('2', '★★'), ('3', '★★★'), ('1', '★'), ('4', '★★★★')], default='★', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='volume',
            field=models.IntegerField(choices=[('5', '★★★★★'), ('2', '★★'), ('3', '★★★'), ('1', '★'), ('4', '★★★★')], default='★', max_length=5),
        ),
    ]
