# Generated by Django 2.1.1 on 2019-08-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20190806_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='fun',
            field=models.CharField(choices=[('5', '★★★★★'), ('1', '★'), ('4', '★★★★'), ('2', '★★'), ('3', '★★★')], default='★', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='runningtime',
            field=models.CharField(choices=[('5', '★★★★★'), ('1', '★'), ('4', '★★★★'), ('2', '★★'), ('3', '★★★')], default='★', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='volume',
            field=models.CharField(choices=[('5', '★★★★★'), ('1', '★'), ('4', '★★★★'), ('2', '★★'), ('3', '★★★')], default='★', max_length=5),
        ),
    ]
