# Generated by Django 2.1.1 on 2019-08-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_auto_20190806_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cnt',
        ),
        migrations.RemoveField(
            model_name='review',
            name='result',
        ),
        migrations.RemoveField(
            model_name='review',
            name='sum',
        ),
        migrations.AlterField(
            model_name='review',
            name='fun',
            field=models.CharField(choices=[('1', '★'), ('4', '★★★★'), ('2', '★★'), ('3', '★★★'), ('5', '★★★★★')], default='★', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='runningtime',
            field=models.CharField(choices=[('1', '★'), ('4', '★★★★'), ('2', '★★'), ('3', '★★★'), ('5', '★★★★★')], default='★', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='volume',
            field=models.CharField(choices=[('1', '★'), ('4', '★★★★'), ('2', '★★'), ('3', '★★★'), ('5', '★★★★★')], default='★', max_length=5),
        ),
    ]
