# Generated by Django 2.1.1 on 2019-08-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_auto_20190806_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='fun',
            field=models.IntegerField(choices=[(3, '★★★'), (5, '★★★★★'), (1, '★'), (2, '★★'), (4, '★★★★')], default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='runningtime',
            field=models.IntegerField(choices=[(3, '★★★'), (5, '★★★★★'), (1, '★'), (2, '★★'), (4, '★★★★')], default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='volume',
            field=models.IntegerField(choices=[(3, '★★★'), (5, '★★★★★'), (1, '★'), (2, '★★'), (4, '★★★★')], default=0, max_length=5),
        ),
    ]
