# Generated by Django 2.1.1 on 2019-08-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_auto_20190806_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='result',
        ),
        migrations.AddField(
            model_name='review',
            name='total',
            field=models.CharField(choices=[('★★★★', '★★★★'), ('★★', '★★'), ('★★★', '★★★'), ('★', '★'), ('★★★★★', '★★★★★')], default='★', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='fun',
            field=models.CharField(choices=[('★★★★', '★★★★'), ('★★', '★★'), ('★★★', '★★★'), ('★', '★'), ('★★★★★', '★★★★★')], default='★', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='runningtime',
            field=models.CharField(choices=[('★★★★', '★★★★'), ('★★', '★★'), ('★★★', '★★★'), ('★', '★'), ('★★★★★', '★★★★★')], default='★', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='volume',
            field=models.CharField(choices=[('★★★★', '★★★★'), ('★★', '★★'), ('★★★', '★★★'), ('★', '★'), ('★★★★★', '★★★★★')], default='★', max_length=5),
        ),
    ]
