# Generated by Django 2.2.3 on 2019-08-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_auto_20190807_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='fun',
            field=models.CharField(choices=[('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★'), ('★', '★'), ('★★', '★★')], default='★', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='runningtime',
            field=models.CharField(choices=[('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★'), ('★', '★'), ('★★', '★★')], default='★', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='total',
            field=models.CharField(choices=[('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★'), ('★', '★'), ('★★', '★★')], default='★', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='volume',
            field=models.CharField(choices=[('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★'), ('★', '★'), ('★★', '★★')], default='★', max_length=5),
        ),
    ]
